USE [master]
GO
/****** Object:  Database [KutuphaneOto]    Script Date: 28.12.2022 02:52:20 ******/
CREATE DATABASE [KutuphaneOto]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'KutuphaneOto', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\KutuphaneOto.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'KutuphaneOto_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\KutuphaneOto_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [KutuphaneOto] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [KutuphaneOto].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [KutuphaneOto] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [KutuphaneOto] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [KutuphaneOto] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [KutuphaneOto] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [KutuphaneOto] SET ARITHABORT OFF 
GO
ALTER DATABASE [KutuphaneOto] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [KutuphaneOto] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [KutuphaneOto] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [KutuphaneOto] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [KutuphaneOto] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [KutuphaneOto] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [KutuphaneOto] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [KutuphaneOto] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [KutuphaneOto] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [KutuphaneOto] SET  DISABLE_BROKER 
GO
ALTER DATABASE [KutuphaneOto] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [KutuphaneOto] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [KutuphaneOto] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [KutuphaneOto] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [KutuphaneOto] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [KutuphaneOto] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [KutuphaneOto] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [KutuphaneOto] SET RECOVERY FULL 
GO
ALTER DATABASE [KutuphaneOto] SET  MULTI_USER 
GO
ALTER DATABASE [KutuphaneOto] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [KutuphaneOto] SET DB_CHAINING OFF 
GO
ALTER DATABASE [KutuphaneOto] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [KutuphaneOto] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [KutuphaneOto] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [KutuphaneOto] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'KutuphaneOto', N'ON'
GO
ALTER DATABASE [KutuphaneOto] SET QUERY_STORE = OFF
GO
USE [KutuphaneOto]
GO
/****** Object:  Table [dbo].[Emanet]    Script Date: 28.12.2022 02:52:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Emanet](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[UyeAd] [nvarchar](50) NOT NULL,
	[KitapAd] [nvarchar](50) NOT NULL,
	[EmanetVerisTarih] [date] NOT NULL,
	[EmanetAlisTarih] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Kitaplar]    Script Date: 28.12.2022 02:52:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Kitaplar](
	[KitapID] [int] IDENTITY(1,1) NOT NULL,
	[kitapSeriNo] [int] NOT NULL,
	[kitapAd] [nvarchar](50) NOT NULL,
	[kitapYazar] [nvarchar](50) NOT NULL,
	[kitapBasimYili] [int] NOT NULL,
	[kitapSayfaSayisi] [int] NOT NULL,
	[kitapYayınevi] [nvarchar](50) NOT NULL,
	[kitapDurum] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Kitaplar] PRIMARY KEY CLUSTERED 
(
	[KitapID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Uyeler]    Script Date: 28.12.2022 02:52:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Uyeler](
	[UyeID] [int] IDENTITY(1,1) NOT NULL,
	[uyeTC] [int] NOT NULL,
	[uyeAdSoyad] [nvarchar](50) NOT NULL,
	[uyeDTarih] [nvarchar](50) NOT NULL,
	[uyeTelefon] [int] NOT NULL,
	[uyeEmail] [nvarchar](50) NOT NULL,
	[uyeAdres] [nvarchar](70) NOT NULL,
 CONSTRAINT [PK_Uyeler] PRIMARY KEY CLUSTERED 
(
	[UyeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [KutuphaneOto] SET  READ_WRITE 
GO
